@Restaurants_API_HostAddress = https://localhost:7072
@token = CfDJ8P2F8u4QqnJFlyMiRvO_GsM-ODG6CKWTeo8qGLazVHR24T9HsFQSI3dJ3andy89phwJdIFcpnrXhunBJ5pi5ralPUAgQSD8pr6Hyfg8BbfSsK0IiPFkV2K8gVdlSL51QxehDt1MDvivjTv8wzYOQKVk5slFR3sL3OqvvMqAkUW1k4XDN6pgnzRpeyeg_QMYCKFAwzykl10dDSklmcoqOD-OOSSm8cZsRcqhcEDiTR6I5Pb6zcAbdRGm9aVHmD3QEISrdHGb9vWD-nF9OSsY1Zi3KeCYty4p4opc9IqafhV9X_cpUE13uidukGa_jz6fdhJkp2_17V9vgOUnWVdmXXtYDQYlM8l3odaoCCFt3VLtmjmz47c-6peH1iQRbyKfsEhzsr2aG4CgweZZb2rRk-aLCJKjymW5NWH-z8ZS9jIqn8dgCgU3mf9BEqlV0WcjQ19_zepe1be0-pdbxlC0HH1WFUZ93oOJRfoo9Rcy3UzzY7Ezak2YPMcSxY6Ze8SPxXqg3U-taxplD3FWKIUmX37eLJuk5BVmYA3dRfvcDjO2JOmQhhb9Y2CsgNOzlsssLaKkI7HJxhqAHmQgnJEXvPBeSis5apcUM8jtCZZv_JUCZHk4tR110mEwaUII7s81wyAha5bquFE6SR-0F79Di5VKjp2JZ1wS9isRFX5tWU6aQoSRdLVXcTt3QtN8_Y4vSU5yazOGnEOv5_Py5PFYdu5g
GET {{Restaurants_API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}

###
GET {{Restaurants_API_HostAddress}}/api/restaurants/10

###
POST {{Restaurants_API_HostAddress}}/register
Content-Type: application/json
{
  "email": "testuser@test.com",
  "password": "password"
}
###

POST {{Restaurants_API_HostAddress}}/register
Content-Type: application/json

{
 "email": "teste@teste.com",
 "password": "pass"
}

###
POST {{Restaurants_API_HostAddress}}/api/restaurants
Content-Type: application/json
{
  "Name" : "ar"
}
###

POST {{Restaurants_API_HostAddress}}/api/restaurants
Content-Type: application/json
{
  
}

###
DELETE {{Restaurants_API_HostAddress}}/api/restaurants/9

###
PATCH {{Restaurants_API_HostAddress}}/api/restaurants/9
Content-Type: application/json
{
 "Name": "Espaço Senac",
 "Description": "Arroz",
 "HasDelivery": false
}

###

POST {{Restaurants_API_HostAddress}}/api/restaurants/10/dishes
Content-Type: application/json

{
  "Name": "Spagthetti Bolognese",
  "Description": "Classic Italian pasta dish with rith meat sauce",
  "Price": 23,
  "KiloCalories": 124
}
###

POST {{Restaurants_API_HostAddress}}/register
Content-Type: application/json
{
  "email": "testuser@test.com",
  "password": "password"
}