@Restaurants_API_HostAddress = https://localhost:7072

GET {{Restaurants_API_HostAddress}}/api/restaurants

###
GET {{Restaurants_API_HostAddress}}/api/restaurants/10

###

POST {{Restaurants_API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "Name": "Espaço pizza",
  "Description": "A sua procura pizza",
  "Category": "Italian",
  "HasDelivery": true,
  "Contactemail": "info@pizza.com",
  "ContactNumber": "555-123-4567",
  "City": "Metropolis",
  "Street": "456 Goumet Avenue",
  "PostalCode": "54-321"
}

###
POST {{Restaurants_API_HostAddress}}/api/restaurants
Content-Type: application/json
{
  "Name" : "ar"
}
###

POST {{Restaurants_API_HostAddress}}/api/restaurants
Content-Type: application/json
{
  
}

###
DELETE {{Restaurants_API_HostAddress}}/api/restaurants/9

###
PATCH {{Restaurants_API_HostAddress}}/api/restaurants/9
Content-Type: application/json
{
 "Name": "Espaço Senac",
 "Description": "Arroz",
 "HasDelivery": false
}

###

POST {{Restaurants_API_HostAddress}}/api/restaurants/10/dishes
Contente-Type: application/json
{
  "Name": "Spagthetti Bolognese",
  "Description": "Classic Italian pasta dish with rith meat sauce",
  "Price": -23,
  "KiloCalories": -1
}
###